
# ===========================
# Database Configuration
# ===========================
spring.datasource.url=jdbc:mysql://localhost:3306/finance_db
spring.datasource.username=financeuser
spring.datasource.password=finance123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# ===========================
# JWT Configuration
# ===========================
app.jwt.secret=zorvyn_super_secret_key_2026_finance_dashboard_khushi
app.jwt.expiration=86400000

# ===========================
# App Info
# ===========================
spring.application.name=finance
server.port=8080